Section "Monitor"
    Identifier "Monitor0"
    # 1280x800 59.81 Hz (CVT 1.02MA) hsync: 49.70 kHz; pclk: 83.50 MHz
    Modeline "1280x800"  83.50  1280 1352 1480 1680  800 803 809 831 -hsync +vsync
    Option "PreferredMode" "1280x800"
EndSection

Section "Device"
    Identifier "Device0"
    Driver "virtio"
EndSection

Section "Screen"
    Identifier "Screen0"
    Device "Device0"
    Monitor "Monitor0"
    DefaultDepth 24
    SubSection "Display"
        Modes "1280x800"
    EndSubSection
EndSection
