#!/bin/bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
IMG="${1:-$ROOT/output/img/qosx.img}"
IMG_SIZE="10G"
BUILD="$ROOT/rootfs/build"
KERNEL_VERSION="6.6.30"
LOOP=""

cleanup() {
  echo "[image] Cleaning up mounts..."
  umount -lf /mnt/qosx/proc     2>/dev/null || true
  umount -lf /mnt/qosx/sys      2>/dev/null || true
  umount -lf /mnt/qosx/dev/pts  2>/dev/null || true
  umount -lf /mnt/qosx/dev      2>/dev/null || true
  umount -lf /mnt/qosx/boot/efi 2>/dev/null || true
  umount -lf /mnt/qosx/boot     2>/dev/null || true
  umount -lf /mnt/qosx          2>/dev/null || true
  [ -n "$LOOP" ] && losetup -d "$LOOP" 2>/dev/null || true
}
trap cleanup EXIT

if [ "$(id -u)" -ne 0 ]; then
  echo "ERROR: image build requires root"
  exit 1
fi

echo "[image] Creating $IMG ($IMG_SIZE)..."
mkdir -p "$(dirname "$IMG")"
qemu-img create -f raw "$IMG" "$IMG_SIZE"

# Partition: GPT, BIOS boot (1MB), EFI (100MB), root (rest)
parted -s "$IMG" \
  mklabel gpt \
  mkpart bios_boot 1MiB 2MiB \
  set 1 bios_grub on \
  mkpart ESP fat32 2MiB 102MiB \
  set 2 esp on \
  mkpart primary ext4 102MiB 100%

# Setup loop device
LOOP=$(losetup --find --partscan --show "$IMG")
echo "[image] Loop: $LOOP"

# Format partitions
mkfs.fat -F32 "${LOOP}p2"
mkfs.ext4 -q "${LOOP}p3"

# Mount
mkdir -p /mnt/qosx
mount "${LOOP}p3" /mnt/qosx
mkdir -p /mnt/qosx/boot/efi
mount "${LOOP}p2" /mnt/qosx/boot/efi

# Copy rootfs
echo "[image] Copying rootfs..."
rsync -a --exclude='/proc/*' --exclude='/sys/*' --exclude='/dev/*' \
  "$BUILD/" /mnt/qosx/

# Copy kernel — versioned filename must match grub.cfg exactly
echo "[image] Copying kernel..."
cp "$ROOT/output/vmlinuz-$KERNEL_VERSION" /mnt/qosx/boot/vmlinuz-$KERNEL_VERSION
cp "$ROOT/config/kernel/kernel.config" /mnt/qosx/boot/config-$KERNEL_VERSION

# Copy initrd — already generated by build-rootfs.sh
echo "[image] Copying initrd..."
if [ -f "$BUILD/boot/initrd.img-$KERNEL_VERSION" ]; then
  cp "$BUILD/boot/initrd.img-$KERNEL_VERSION" /mnt/qosx/boot/initrd.img-$KERNEL_VERSION
  echo "[image] initrd: OK"
else
  echo "[image] initrd not in rootfs/build — generating..."
  mount --bind /proc /mnt/qosx/proc
  mount --bind /sys  /mnt/qosx/sys
  mount --bind /dev  /mnt/qosx/dev
  mount --bind /dev/pts /mnt/qosx/dev/pts
  chroot /mnt/qosx update-initramfs -c -k "$KERNEL_VERSION"
  umount /mnt/qosx/dev/pts /mnt/qosx/proc /mnt/qosx/sys /mnt/qosx/dev
fi

# Verify before GRUB install
echo "[image] Boot directory:"
ls -lh /mnt/qosx/boot/
[ ! -f "/mnt/qosx/boot/vmlinuz-$KERNEL_VERSION" ]   && echo "ERROR: vmlinuz missing"  && exit 1
[ ! -f "/mnt/qosx/boot/initrd.img-$KERNEL_VERSION" ] && echo "ERROR: initrd missing"   && exit 1

# Install GRUB (BIOS + EFI)
echo "[image] Installing GRUB..."
grub-install \
  --target=i386-pc \
  --boot-directory=/mnt/qosx/boot \
  --recheck \
  "$LOOP"

grub-install \
  --target=x86_64-efi \
  --efi-directory=/mnt/qosx/boot/efi \
  --boot-directory=/mnt/qosx/boot \
  --removable \
  --recheck

# Install GRUB config
cp "$ROOT/config/grub/grub.cfg" /mnt/qosx/boot/grub/grub.cfg

# Set ownership back to the invoking user if run via sudo
if [ -n "${SUDO_UID:-}" ] && [ -n "${SUDO_GID:-}" ]; then
  chown "$SUDO_UID:$SUDO_GID" "$IMG"
fi

echo "[image] Done: $IMG"